const articles = [
  {
    id: 1,
    title: "How to reset your password securely using self-service tools",
    category: "Security",
    system: "User Portal",
    updatedAt: "May 18, 2025",
    author: "Jane Wanjiku",
    description:
      "Learn how to reset your password quickly and securely without needing support.",
    tags: ["configuration", "#password", "#login"],
    readTime: "2 min read",
  },
  {
    id: 2,
    title: "Understanding how ticket escalation works in our system",
    category: "Support",
    system: "Helpdesk",
    updatedAt: "May 20, 2025",
    author: "John Mutai",
    description:
      "An overview of the ticket escalation process, including SLAs and escalation levels.",
    tags: ["#support", "#tickets", "#escalation"],
    readTime: "3 min read",
  },
  {
    id: 3,
    title: "Connecting to the VPN remotely from any device",
    category: "Network",
    system: "IT Infrastructure",
    updatedAt: "May 15, 2025",
    author: "Brian Okoth",
    description:
      "Step-by-step guide on connecting to the company VPN using Windows or Mac.",
    tags: ["#vpn", "#remote", "#network"],
    readTime: "4 min read",
  },
  {
    id: 4,
    title: "Troubleshooting Email Delivery Issues in Outlook and Gmail",
    category: "Communication",
    system: "Email Services",
    updatedAt: "May 10, 2025",
    author: "Mary Atieno",
    tags: ["#security", "#login"],
    description: "Learn how to reset your password safely and quickly.",
    readTime: "2 min read",
  },
  {
    id: 5,
    title: "How to Submit a Support Ticket and Track Its Progress",
    category: "Support",
    system: "ZahraDesk",
    updatedAt: "May 22, 2025",
    author: "Elijah Kibet",
    tags: ["#security", "#login"],
    description: "Learn how to reset your password safely and quickly.",
    readTime: "2 min read",
  },
  {
    id: 6,
    title: "Installing and Configuring the ZahraDesk Desktop App",
    category: "Getting Started",
    system: "ZahraDesk",
    updatedAt: "May 23, 2025",
    author: "Faith Nyambura",
    tags: ["#security", "#login"],
    description: "Learn how to reset your password safely and quickly.",
    readTime: "2 min read",
  },
  {
    id: 7,
    title: "Setting Up Two-Factor Authentication for Extra Security",
    category: "Security",
    system: "User Portal",
    updatedAt: "May 21, 2025",
    author: "Peter Omondi",
    tags: ["#security", "#login"],
    description: "Learn how to reset your password safely and quickly.",
    readTime: "2 min read",
  },
  {
    id: 8,
    title: "Managing Your Team’s Access Rights and Permissions",
    category: "Administration",
    system: "Admin Console",
    updatedAt: "May 19, 2025",
    author: "Linet Cherono",
    tags: ["#security", "#login"],
    description: "Learn how to reset your password safely and quickly.",
    readTime: "2 min read",
  },
];

export default articles;